### ISSUE TITLE
Issue with large count categorical values

### ISSUE THREAD

**Issue by SDS-Architect** [gherka/summarize_two#1]
Excellent work and very clear visualisation! There is an issue with high cardinality variables (e.g. main condition) whereby the system counts the number of unique values correctly, but does not actually count and display the differences between the individual conditions. Is there a way to rectify this?

**Comment by gherka** [comment]
As a new feature I think there should be a button to open up any visualisation in a new window in "full size" + table of values underneath for easy exporting.

**Comment by SDS-Architect** [comment]
I agree as it shouldn't be a common problem, great work!
